INSERT INTO exercise_template (name) VALUES
                                         ('Martwy ciąg'),
                                         ('Przysiad ze sztangą'),
                                         ('Przysiad ze sztangą na klatkę'),
                                         ('Wyciskanie na ławce poziomej ze sztangą'),
                                         ('Wyciskanie na ławce poziomej z hantlami'),
                                         ('Wyciskanie na ławce skośnej ze sztangą'),
                                         ('Wyciskanie na ławce skośnej z hantlami'),
                                         ('Wiosłowanie sztangą'),
                                         ('Podciąganie na drążku'),
                                         ('Pompki'),
                                         ('Wyciskanie żołnierskie'),
                                         ('Uginanie ramion ze sztangą'),
                                         ('Prostowanie ramion na wyciągu'),
                                         ('Wypychanie nóg na suwnicy'),
                                         ('Unoszenie nóg w zwisie'),
                                         ('Plank'),
                                         ('Skłony boczne z hantlem'),
                                         ('Przysiady bułgarskie'),
                                         ('Podciąganie hantli w opadzie'),
                                         ('Wznosy boczne hantli'),
                                         ('Hip thrust'),
                                         ('Face pull'),
                                         ('Brzuszki'),
                                         ('Wyciskanie francuskie'),
                                         ('Wspięcia na palce stojąc'),
                                         ('Przysiady z kettlebellem'),
                                         ('Mountain climbers'),
                                         ('Burpees'),
                                         ('Swing z kettlebellem'),
                                         ('Rozpiętki na ławce poziomej'),
                                         ('Rozpiętki na ławce skośnej'),
                                         ('Przeciąganie liny (battle ropes)'),
                                         ('Pompki na poręczach (dipy)'),
                                         ('Wspięcia na palce siedząc'),
                                         ('Skakanka'),
                                         ('Unoszenie hantli przed siebie'),
                                         ('Wyciskanie hantli na ławce płaskiej'),
                                         ('Wyciskanie hantli na ławce skośnej'),
                                         ('Przysiad sumo'),
                                         ('Martwy ciąg na prostych nogach'),
                                         ('Uginanie ramion z hantlami na modlitewniku'),
                                         ('Plank boczny'),
                                         ('Wspięcia na palce z hantlami'),
                                         ('Podciąganie australijskie'),
                                         ('Wyciskanie na maszynie Smitha'),
                                         ('Wyciskanie na maszynie na ławce poziomej'),
                                         ('Przysiady na hack-maszynie'),
                                         ('Wypychanie nóg na suwnicy jednonóż'),
                                         ('Pompki diamentowe'),
                                         ('Pompki z klaśnięciem'),
                                         ('Deska na piłce fitness'),
                                         ('Unoszenie bioder leżąc (glute bridge)'),
                                         ('Wznosy łydek na stepie'),
                                         ('Wyciskanie francuskie hantlami'),
                                         ('Ściąganie drążka górnego szerokim nachwytem'),
                                         ('Ściąganie drążka wąskim nachwytem'),
                                         ('Wiosłowanie jednorącz hantlą'),
                                         ('Unoszenie ramion w opadzie tułowia'),
                                         ('Wyciskanie kettlebella nad głową'),
                                         ('Wykroki z hantlami'),
                                         ('Mostek biodrowy na jednej nodze'),
                                         ('Rosyjskie skręty z piłką lekarską');